# Generated by Django 4.2.7 on 2025-01-24 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_remove_student_department_alter_course_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='code',
        ),
        migrations.RemoveField(
            model_name='programme',
            name='code',
        ),
    ]
