# Generated by Django 5.0.6 on 2025-01-25 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_remove_student_roll_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='semester',
            field=models.IntegerField(default=0),
        ),
    ]
