# Generated by Django 5.0.6 on 2025-01-25 04:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_course_semester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='code',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='course',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.department'),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='course',
            name='semester',
            field=models.CharField(choices=[('1', 'First Semester'), ('2', 'Second Semester'), ('3', 'Third Semester'), ('4', 'Fourth Semester'), ('5', 'Fifth Semester'), ('6', 'Sixth Semester'), ('7', 'Seventh Semester'), ('8', 'Eighth Semester')], max_length=1),
        ),
    ]
