# Generated by Django 4.2.7 on 2025-01-25 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0007_alter_course_code_alter_course_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hourdatecourse',
            name='year',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='hourdatecourse',
            name='hour',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='hourdatecourse',
            unique_together={('teacher_course', 'date', 'hour', 'year')},
        ),
    ]
