# Generated by Django 4.2.7 on 2025-01-25 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0008_hourdatecourse_year_alter_hourdatecourse_hour_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hourdatecourse',
            name='year',
            field=models.IntegerField(),
        ),
    ]
