# Generated by Django 4.2.7 on 2025-01-25 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0009_alter_hourdatecourse_year'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='hourdatecourse',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='studentcourse',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='teachercourse',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='studentcourse',
            name='year',
            field=models.PositiveIntegerField(default=2024, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teachercourse',
            name='year',
            field=models.PositiveIntegerField(default=2024, editable=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hourdatecourse',
            name='year',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterUniqueTogether(
            name='studentcourse',
            unique_together={('student', 'course', 'year')},
        ),
        migrations.AlterUniqueTogether(
            name='teachercourse',
            unique_together={('teacher', 'course', 'year')},
        ),
    ]
