# Generated by Django 4.2.7 on 2025-01-25 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0010_alter_hourdatecourse_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='year_offered',
        ),
    ]
