# Generated by Django 4.2.7 on 2025-01-25 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0011_remove_course_year_offered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hourdatecourse',
            name='hour',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Hour 1'), (2, 'Hour 2'), (3, 'Hour 3'), (4, 'Hour 4'), (5, 'Hour 5')]),
        ),
    ]
