# Generated by Django 4.2.7 on 2025-01-25 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0012_alter_hourdatecourse_hour'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='absentdetails',
            unique_together=set(),
        ),
    ]
