# Generated by Django 4.2.7 on 2025-01-25 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0013_alter_absentdetails_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='absentdetails',
            unique_together={('student', 'hour_date_course')},
        ),
        migrations.AlterUniqueTogether(
            name='hourdatecourse',
            unique_together={('date', 'hour')},
        ),
    ]
