# Generated by Django 4.2.7 on 2025-01-25 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0015_alter_hourdatecourse_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='hourdatecourse',
            unique_together={('date', 'hour', 'teacher_course')},
        ),
    ]
