# Generated by Django 4.2.7 on 2025-01-26 01:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0016_alter_hourdatecourse_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='hourdatecourse',
            unique_together={('date', 'hour')},
        ),
        migrations.AddField(
            model_name='hourdatecourse',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='attendance.course'),
        ),
        migrations.AddField(
            model_name='hourdatecourse',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='attendance.teacher'),
        ),
        migrations.RemoveField(
            model_name='hourdatecourse',
            name='teacher_course',
        ),
    ]
