# Generated by Django 4.2.7 on 2025-01-26 01:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0017_alter_hourdatecourse_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hourdatecourse',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.course'),
        ),
        migrations.AlterField(
            model_name='hourdatecourse',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.teacher'),
        ),
    ]
