# Generated by Django 4.2.7 on 2025-01-26 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0018_alter_hourdatecourse_course_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='hourdatecourse',
            unique_together={('course', 'date', 'hour')},
        ),
    ]
