# Generated by Django 5.0.6 on 2025-02-13 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0019_alter_hourdatecourse_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='roll_number',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
