# Generated by Django 5.1.6 on 2025-07-24 16:38

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0021_student_year_of_enrolment_batch_teacherbatch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hourdatebatch',
            name='batch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='attendance.batch'),
        ),
        migrations.AddField(
            model_name='hourdatebatch',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='attendance.teacher'),
        ),
        migrations.AddField(
            model_name='student',
            name='current_semester',
            field=models.PositiveSmallIntegerField(default=1, help_text='Semester 1 to 8. Set to 0 after pass out.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(8)]),
        ),
        migrations.AlterUniqueTogether(
            name='hourdatebatch',
            unique_together={('batch', 'date', 'hour')},
        ),
    ]
