# Generated by Django 5.1.6 on 2025-07-24 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0022_alter_hourdatebatch_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hourdatebatch',
            name='teacher_batch',
        ),
    ]
