# Generated by Django 5.1.6 on 2025-07-27 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0023_remove_hourdatebatch_teacher_batch'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='hourdatecourse',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='hourdatecourse',
            name='course',
        ),
        migrations.RemoveField(
            model_name='hourdatecourse',
            name='teacher',
        ),
        migrations.AlterUniqueTogether(
            name='studentcourse',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='studentcourse',
            name='course',
        ),
        migrations.RemoveField(
            model_name='studentcourse',
            name='student',
        ),
        migrations.AlterUniqueTogether(
            name='teachercourse',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='teachercourse',
            name='course',
        ),
        migrations.RemoveField(
            model_name='teachercourse',
            name='teacher',
        ),
        migrations.DeleteModel(
            name='AbsentDetails',
        ),
        migrations.DeleteModel(
            name='HourDateCourse',
        ),
        migrations.DeleteModel(
            name='StudentCourse',
        ),
        migrations.DeleteModel(
            name='TeacherCourse',
        ),
    ]
