# Generated by Django 5.1.6 on 2025-07-27 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0024_alter_hourdatecourse_unique_together_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NewAbsentDetails',
            new_name='AbsentDetails',
        ),
    ]
