# Generated by Django 5.1.6 on 2025-08-02 08:42

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0025_rename_newabsentdetails_absentdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='TC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('current_semester', models.PositiveSmallIntegerField(help_text='The semester in which the student applied for TC.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(8)])),
                ('year_of_tc', models.PositiveIntegerField(default=2025)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tcs', to='attendance.student')),
            ],
        ),
    ]
