# Generated by Django 5.0.6 on 2025-07-28 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0025_rename_newabsentdetails_absentdetails'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AbsentDetails',
            new_name='NewAbsentDetails',
        ),
    ]
