# Generated by Django 5.0.6 on 2025-07-28 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0026_rename_absentdetails_newabsentdetails'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NewAbsentDetails',
            new_name='AbsentDetails',
        ),
    ]
