# Generated by Django 5.1.6 on 2025-08-07 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0026_tc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='university_register_number',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
