# Generated by Django 5.0.6 on 2025-08-02 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0028_tc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tc',
            old_name='current_semester',
            new_name='leaving_semester',
        ),
    ]
