# Generated by Django 5.1.6 on 2025-08-07 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0028_alter_student_roll_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='university_register_number',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
