# Generated by Django 5.0.6 on 2025-08-02 10:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0029_rename_current_semester_tc_leaving_semester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tc',
            name='leaving_semester',
            field=models.PositiveSmallIntegerField(help_text='Semester completed at the time of TC application.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(8)]),
        ),
    ]
