# Generated by Django 5.1.6 on 2025-08-07 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0029_alter_student_university_register_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='university_register_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
