# Generated by Django 5.0.6 on 2025-08-07 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0030_alter_tc_leaving_semester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='roll_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='university_register_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
