# Generated by Django 5.1.6 on 2025-08-09 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0030_alter_student_university_register_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='acronym',
            field=models.CharField(blank=True, help_text='E.g., AR for Abhinav Raj', max_length=10, null=True),
        ),
    ]
