# Generated by Django 5.1.6 on 2025-08-20 17:31

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0031_teacher_acronym'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester_completed', models.PositiveSmallIntegerField(help_text='Number of semesters completed before transfer.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(8)])),
                ('year_of_transfer', models.PositiveIntegerField(default=2025)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('department_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_from', to='attendance.department')),
                ('department_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_to', to='attendance.department')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='attendance.student')),
            ],
            options={
                'verbose_name': 'Student Transfer',
                'verbose_name_plural': 'Student Transfers',
                'ordering': ['-year_of_transfer'],
            },
        ),
    ]
