# Generated by Django 5.0.6 on 2025-08-09 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0031_alter_student_roll_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='acronym',
            field=models.CharField(blank=True, help_text='E.g., AR for Abhinav Raj', max_length=10, null=True),
        ),
    ]
