# Generated by Django 4.2.30 on 2026-07-09 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0033_studenttransfer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absentdetails',
            name='hour_date_batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='attendance.hourdatebatch'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='academic_year',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='batch',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='attendance.course'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='part',
            field=models.CharField(choices=[('A', 'Part A'), ('B', 'Part B')], max_length=1),
        ),
        migrations.AlterField(
            model_name='studenttransfer',
            name='year_of_transfer',
            field=models.PositiveIntegerField(default=2026),
        ),
        migrations.AlterField(
            model_name='tc',
            name='year_of_tc',
            field=models.PositiveIntegerField(default=2026),
        ),
        migrations.AlterUniqueTogether(
            name='batch',
            unique_together={('course', 'academic_year', 'part')},
        ),
        migrations.CreateModel(
            name='GraceAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=255)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('hour_date_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grace_attendances', to='attendance.hourdatebatch')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grace_records', to='attendance.student')),
            ],
            options={
                'unique_together': {('student', 'hour_date_batch')},
            },
        ),
    ]
